# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91ff5f1a511194b47d43170957ac72013b7ed489cc69dedafe96990558b27d8c3a04d6ac991f9271cc980b78289a23fd75fdc75aaee56a99a286db10fd24b582

test:
  secret_key_base: c5fe2da5800be0527fec2afa76d5defdfff465641a8c8183b4894fb4611bc145840f463764daba4a552e3fe0ba441a6aa48f2740969e1584c6cd554582be452b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
